name = "gdax-diagnostic"
compatibility_date = "2024-12-01"
pages_build_output_dir = "./public"

[[d1_databases]]
binding = "DB"
database_name = "gdax-assessments"
database_id = "a4599a8b-8d19-4d33-9959-26e68bd88c18"
